__all__ = [
    "AggregateFunction",
    "Array",
    "Boolean",
    "Date",
    "Date32",
    "DateTime",
    "DateTime64",
    "Decimal",
    "Enum",
    "Enum8",
    "Enum16",
    "Float",
    "Float32",
    "Float64",
    "Int",
    "Int8",
    "Int16",
    "Int32",
    "Int64",
    "Int128",
    "Int256",
    "IPv4",
    "IPv6",
    "JSON",
    "LowCardinality",
    "Map",
    "Nested",
    "Nullable",
    "SimpleAggregateFunction",
    "String",
    "Tuple",
    "UInt8",
    "UInt16",
    "UInt32",
    "UInt64",
    "UInt128",
    "UInt256",
    "UUID",
]

from clickhouse_sqlalchemy.types import (
    AggregateFunction,
    Array,
    Boolean,
    Date,
    Date32,
    DateTime,
    DateTime64,
    Decimal,
    Enum,
    Enum8,
    Enum16,
    Float,
    Float32,
    Float64,
    Int,
    Int8,
    Int16,
    Int32,
    Int64,
    Int128,
    Int256,
    IPv4,
    IPv6,
    JSON,
    LowCardinality,
    Map,
    Nested,
    Nullable,
    SimpleAggregateFunction,
    String,
    Tuple,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    UInt128,
    UInt256,
    UUID,
)
from clickhouse_sqlalchemy.types.common import ClickHouseTypeEngine
from sqlalchemy import TypeDecorator

import json


class JSONString(TypeDecorator, String, ClickHouseTypeEngine):
    __visit_name__ = "string"
    impl = String

    def process_bind_param(self, value, dialect):
        return json.dumps(value)
